apiVersion: v1
kind: Secret
metadata:
  name: pawpal-secrets
  namespace: pawpal
type: Opaque
stringData:
  database-url: REPLACE_WITH_EXTERNAL_SECRET_REFERENCE
  jwt-secret: REPLACE_WITH_EXTERNAL_SECRET_REFERENCE
