apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pawpal.fullname" . }}-api
  labels:
    {{- include "pawpal.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pawpal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "pawpal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ include "pawpal.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: database-migration
          image: {{ include "pawpal.apiImage" . | quote }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["npx", "prisma", "migrate", "deploy"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "pawpal.secretName" . }}
                  key: {{ .Values.secrets.databaseUrlKey }}
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 250m, memory: 256Mi }
          volumeMounts:
            - name: migration-tmp
              mountPath: /tmp
      containers:
        - name: api
          image: {{ include "pawpal.apiImage" . | quote }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "pawpal.fullname" . }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "pawpal.secretName" . }}
                  key: {{ .Values.secrets.databaseUrlKey }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "pawpal.secretName" . }}
                  key: {{ .Values.secrets.jwtSecretKey }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
          readinessProbe:
            httpGet: { path: /api/health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /api/health, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: migration-tmp
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
