{{- if .Values.secrets.create }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "pawpal.secretName" .) }}
{{- $databasePassword := randAlphaNum 32 }}
{{- $jwtSecret := randAlphaNum 48 }}
{{- if $existing }}
{{- $databasePassword = (index $existing.data "password" | b64dec) }}
{{- $jwtSecret = (index $existing.data .Values.secrets.jwtSecretKey | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pawpal.secretName" . }}
  labels:
    {{- include "pawpal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.databaseUrlKey }}: {{ default (printf "%s//%s:%s@%s-postgresql:5432/%s?schema=public" "postgresql:" .Values.postgresql.auth.username $databasePassword .Release.Name .Values.postgresql.auth.database) .Values.secrets.databaseUrl | quote }}
  {{ .Values.secrets.jwtSecretKey }}: {{ default $jwtSecret .Values.secrets.jwtSecret | quote }}
  password: {{ $databasePassword | quote }}
  postgres-password: {{ $databasePassword | quote }}
{{- end }}
