apiVersion: v1
kind: Service
metadata:
  name: {{ include "pawpal.fullname" . }}-api
  labels:
    {{- include "pawpal.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pawpal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pawpal.fullname" . }}-web
  labels:
    {{- include "pawpal.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pawpal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
