name: Validate Helm chart

on:
  pull_request:
    paths:
      - "charts/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  dev:
    uses: raja1417/github-actions-workflows/.github/workflows/helm-validate.yml@v1
    with:
      chart-path: charts/pawpal
      values-file: values-dev.yaml

  prod:
    uses: raja1417/github-actions-workflows/.github/workflows/helm-validate.yml@v1
    with:
      chart-path: charts/pawpal
      values-file: values-prod.yaml
