name: Infrastructure security

on:
  pull_request:
    paths:
      - "infrastructure/**"

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  tfsec:
    uses: raja1417/github-actions-workflows/.github/workflows/tfsec-scan.yml@46f7f73286ef3fbd947e8f317c2b88262cf3c6af
    with:
      working-directory: infrastructure

  checkov:
    uses: raja1417/github-actions-workflows/.github/workflows/checkov-scan.yml@46f7f73286ef3fbd947e8f317c2b88262cf3c6af
    with:
      directory: infrastructure
      framework: terraform
